version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: 
              pwd
      - run:
          command: cd test | 
      - run:
          command: ls -lh
      - run:
          command: python -m unittest
          
workflows:
  main:
    jobs:
      - test
