version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    working_directory: ~/test
    executor: python/default
    steps:
      - checkout
      - run:
          command: ls -lh
      - run:
          command: python -m unittest
          
workflows:
  main:
    jobs:
      - test
